package org.unhcr.osmosys.model.enums;

public enum DissagregationType implements EnumInterface {
    SIN_DESAGREGACION("Sin Desagregación", 9),
    //
    TIPO_POBLACION("Tipo de población", 1),
    EDAD("Edad", 2),
    GENERO("Género", 5),
    DIVERSIDAD("Diversidad", 8),
    PAIS_ORIGEN("País de Origen", 7),
    LUGAR("Lugar", 6),


    // 2

    TIPO_POBLACION_EDAD("Tipo de población y Edad", 1),
    TIPO_POBLACION_GENERO("Tipo de población y GENERO", 1),
    TIPO_POBLACION_DIVERSIDAD("Tipo de población y DIVERSIDAD", 1),
    TIPO_POBLACION_PAIS_ORIGEN("Tipo de población y PAIS_ORIGEN", 1),
    TIPO_POBLACION_LUGAR("Tipo de población y LUGAR", 1),
    EDAD_GENERO("Edad y GENERO", 1),
    EDAD_DIVERSIDAD("Edad y DIVERSIDAD", 1),
    EDAD_PAIS_ORIGEN("Edad y PAIS_ORIGEN", 1),
    EDAD_LUGAR("Edad y LUGAR", 1),
    GENERO_DIVERSIDAD("GENERO y DIVERSIDAD", 1),
    GENERO_PAIS_ORIGEN("GENERO y PAIS_ORIGEN", 1),
    GENERO_LUGAR("GENERO y LUGAR", 1),
    DIVERSIDAD_PAIS_ORIGEN("DIVERSIDAD y PAIS_ORIGEN", 1),
    DIVERSIDAD_LUGAR("DIVERSIDAD y LUGAR", 1),
    PAIS_ORIGEN_LUGAR("PAIS_ORIGEN y LUGAR", 1),

    // 3

    TIPO_POBLACION_EDAD_GENERO("Tipo de población, Edad y GENERO", 1),
    TIPO_POBLACION_EDAD_DIVERSIDAD("Tipo de población, Edad y DIVERSIDAD", 1),
    TIPO_POBLACION_EDAD_PAIS_ORIGEN("Tipo de población, Edad y PAIS_ORIGEN", 1),
    TIPO_POBLACION_EDAD_LUGAR("Tipo de población, Edad y LUGAR", 1),
    TIPO_POBLACION_GENERO_DIVERSIDAD("Tipo de población, GENERO y DIVERSIDAD", 1),
    TIPO_POBLACION_GENERO_PAIS_ORIGEN("Tipo de población, GENERO y PAIS_ORIGEN", 1),
    TIPO_POBLACION_GENERO_LUGAR("Tipo de población, GENERO y LUGAR", 1),
    TIPO_POBLACION_DIVERSIDAD_PAIS_ORIGEN("Tipo de población, DIVERSIDAD y PAIS_ORIGEN", 1),
    TIPO_POBLACION_DIVERSIDAD_LUGAR("Tipo de población, DIVERSIDAD y LUGAR", 1),
    TIPO_POBLACION_PAIS_ORIGEN_LUGAR("Tipo de población, PAIS_ORIGEN y LUGAR", 1),
    EDAD_GENERO_DIVERSIDAD("Edad, GENERO y DIVERSIDAD", 1),
    EDAD_GENERO_PAIS_ORIGEN("Edad, GENERO y PAIS_ORIGEN", 1),
    EDAD_GENERO_LUGAR("Edad, GENERO y LUGAR", 1),
    EDAD_DIVERSIDAD_PAIS_ORIGEN("Edad, DIVERSIDAD y PAIS_ORIGEN", 1),
    EDAD_DIVERSIDAD_LUGAR("Edad, DIVERSIDAD y LUGAR", 1),
    EDAD_PAIS_ORIGEN_LUGAR("Edad, PAIS_ORIGEN y LUGAR", 1),
    GENERO_DIVERSIDAD_PAIS_ORIGEN("GENERO, DIVERSIDAD y PAIS_ORIGEN", 1),
    GENERO_DIVERSIDAD_LUGAR("GENERO, DIVERSIDAD y LUGAR", 1),
    GENERO_PAIS_ORIGEN_LUGAR("GENERO, PAIS_ORIGEN y LUGAR", 1),
    DIVERSIDAD_PAIS_ORIGEN_LUGAR("DIVERSIDAD, PAIS_ORIGEN y LUGAR", 1),

    TIPO_POBLACION_EDAD__GENERO_DIVERSIDAD("Tipo de población, Edad, GENERO y DIVERSIDAD", 1),
    TIPO_POBLACION_EDAD__GENERO_PAIS_ORIGEN("Tipo de población, Edad, GENERO y PAIS_ORIGEN", 1),
    TIPO_POBLACION_EDAD__GENERO_LUGAR("Tipo de población, Edad, GENERO y LUGAR", 1),
    TIPO_POBLACION_EDAD__DIVERSIDAD_PAIS_ORIGEN("Tipo de población, Edad, DIVERSIDAD y PAIS_ORIGEN", 1),
    TIPO_POBLACION_EDAD__DIVERSIDAD_LUGAR("Tipo de población, Edad, DIVERSIDAD y LUGAR", 1),
    TIPO_POBLACION_EDAD__PAIS_ORIGEN_LUGAR("Tipo de población, Edad, PAIS_ORIGEN y LUGAR", 1),
    TIPO_POBLACION_GENERO__DIVERSIDAD_PAIS_ORIGEN("Tipo de población, GENERO, DIVERSIDAD y PAIS_ORIGEN", 1),
    TIPO_POBLACION_GENERO__DIVERSIDAD_LUGAR("Tipo de población, GENERO, DIVERSIDAD y LUGAR", 1),
    TIPO_POBLACION_GENERO__PAIS_ORIGEN_LUGAR("Tipo de población, GENERO, PAIS_ORIGEN y LUGAR", 1),
    TIPO_POBLACION_DIVERSIDAD__PAIS_ORIGEN_LUGAR("Tipo de población, DIVERSIDAD, PAIS_ORIGEN y LUGAR", 1),
    EDAD_GENERO__DIVERSIDAD_PAIS_ORIGEN("Edad, GENERO, DIVERSIDAD y PAIS_ORIGEN", 1),
    EDAD_GENERO__DIVERSIDAD_LUGAR("Edad, GENERO, DIVERSIDAD y LUGAR", 1),
    EDAD_GENERO__PAIS_ORIGEN_LUGAR("Edad, GENERO, PAIS_ORIGEN y LUGAR", 1),
    EDAD_DIVERSIDAD__PAIS_ORIGEN_LUGAR("Edad, DIVERSIDAD, PAIS_ORIGEN y LUGAR", 1),
    GENERO_DIVERSIDAD__PAIS_ORIGEN_LUGAR("GENERO, DIVERSIDAD, PAIS_ORIGEN y LUGAR", 1),

    // 5
    TIPO_POBLACION_EDAD_GENERO_DIVERSIDAD_PAIS_ORIGEN("Tipo de población, Edad, GENERO, DIVERSIDAD, PAIS_ORIGEN", 1),
    TIPO_POBLACION_EDAD_GENERO_DIVERSIDAD_LUGAR("Tipo de población, Edad, GENERO, DIVERSIDAD, LUGAR", 1),
    TIPO_POBLACION_EDAD_GENERO_PAIS_ORIGEN_LUGAR("Tipo de población, Edad, GENERO, PAIS_ORIGEN, LUGAR", 1),
    TIPO_POBLACION_EDAD_DIVERSIDAD_PAIS_ORIGEN_LUGAR("Tipo de población, Edad, DIVERSIDAD, PAIS_ORIGEN, LUGAR", 1),
    TIPO_POBLACION_GENERO_DIVERSIDAD_PAIS_ORIGEN_LUGAR("Tipo de población, GENERO, DIVERSIDAD, PAIS_ORIGEN, LUGAR", 1),
    EDAD_GENERO_DIVERSIDAD_PAIS_ORIGEN_LUGAR("Edad, GENERO, DIVERSIDAD, PAIS_ORIGEN, LUGAR", 1);



    private String label;
    private final int order;

    DissagregationType(String label, int order) {
        this.label = label;
        this.order = order;
    }

    @Override
    public String getStringValue() {
        return this.name();
    }

    public String getLabel() {
        return label;
    }

    @Override
    public int getOrder() {
        return this.order;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    }