package com.sagatechs.generics.appConfiguration;

public enum AppConfigurationKey {
	EMAIL_SMTP, EMAIL_TLS, EMAIL_SMTP_HOST,EMAIL_SMTP_PORT, EMAIL_USERNAME, EMAIL_PASSOWRD, EMAIL_ADDRES, FILE_DIRECTORY,  REMINDER_DAYS, REPORT_LIMIT, IM_EMAIL, PROGRAMS_EMAIL,
	APP_URL, CAN_PARTNER_EDIT_LOCATION, CAN_UNHCR_EDIT_LOCATION, TIME_ZONE, PROJECTS_REMINDER_EMAIL, DIRECT_IMPLS_REMINDER_EMAIL, PROJECTS_ALERT_EMAIL, DIRECT_IMPLS_ALERT_EMAIL,
	NEW_USER_NOTIFICATION_EMAIL, RESULT_MANAGER_REMINDER_EMAIL, RESULT_MANAGER_ALERT_EMAIL

}